version: '3.8'
services:
  cache:
    image: redis:7.0-rc1-bullseye
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - redis-cache:/data
volumes:
  redis-cache:
    driver: local
